import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <article className="space-y-10">
      <header className="space-y-4 pb-8 border-b border-border/30">
        <p className="text-[10px] font-mono uppercase tracking-[0.3em] text-muted">Legal</p>
        <h1 className="text-4xl font-bold tracking-tighter">Terms of Service</h1>
        <div className="flex gap-6 text-xs font-mono text-muted">
          <span>Effective: April 5, 2026</span>
          <span>Last Updated: April 5, 2026</span>
        </div>
      </header>

      <div className="space-y-10 text-sm leading-relaxed text-white/70">
        <section className="space-y-4">
          <p>These Terms of Service (&quot;Terms&quot;) govern your access to and use of vaibrant.agency and all products and services operated by Vaibrant Agency (&quot;Vaibrant,&quot; &quot;we,&quot; &quot;us&quot;), including AI agent development, workflow automation, advertising management platforms, and consulting services (collectively, the &quot;Services&quot;). By using our Services, you agree to these Terms.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">1. Acceptance and Eligibility</h2>
          <p>You must be at least 18 years old and have legal authority to bind the organization on whose behalf you engage our Services. By accepting these Terms, you represent that you have such authority.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">2. Services Description</h2>
          <p>Vaibrant provides AI-powered business services, including:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Autonomous AI agent development and deployment</li>
            <li>Workflow and platform automation (Make.com, n8n, Google Workspace)</li>
            <li>AI-powered advertising management (Quantum Ads)</li>
            <li>Data intelligence, analytics, and growth systems</li>
            <li>AI strategy consulting and implementation</li>
          </ul>
          <p>Certain services integrate with third-party platforms (Meta, Google, etc.). Service availability depends on those platforms&apos; uptime and your granted permissions.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">3. Account Terms</h2>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Provide accurate, complete information and keep it updated</li>
            <li>Maintain security of your account credentials</li>
            <li>Do not share credentials or allow unauthorized access</li>
            <li>You are responsible for all activities under your account</li>
            <li>Connect third-party platforms via OAuth only — never share platform passwords</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">4. Third-Party Platform Compliance</h2>
          <p>When our Services integrate with third-party platforms, you agree to comply with those platforms&apos; terms of service, advertising standards, and community guidelines. We may suspend access if a platform notifies us of policy violations on your account.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">5. Acceptable Use</h2>
          <p>Your use is subject to our <Link href="/acceptable-use" className="text-foreground underline underline-offset-4">Acceptable Use Policy</Link>, incorporated by reference. Violations constitute a breach of these Terms.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">6. Intellectual Property</h2>
          <h3 className="text-base font-semibold text-foreground mt-4">6.1 Our Property</h3>
          <p>The Services, including software, algorithms, AI models, interfaces, documentation, and all related IP, are owned by Vaibrant and protected by applicable law.</p>
          <h3 className="text-base font-semibold text-foreground mt-4">6.2 Your Content</h3>
          <p>You retain ownership of your business data, creative assets, and content. You grant us a limited license to process it solely to provide the Services, terminating when you delete your data or close your account.</p>
          <h3 className="text-base font-semibold text-foreground mt-4">6.3 AI-Generated Content</h3>
          <p>Content generated by our AI systems based on your inputs is provided for your use. You are responsible for reviewing, approving, and ensuring compliance of all AI-generated content.</p>
          <h3 className="text-base font-semibold text-foreground mt-4">6.4 Aggregated Data</h3>
          <p>We may use anonymized, aggregated data to improve our platform and generate industry insights. Such data cannot identify you or your business.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">7. Payment Terms</h2>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>Service pricing as displayed or agreed upon in your service agreement</li>
            <li>Subscriptions auto-renew unless cancelled before the billing cycle ends</li>
            <li>Pricing changes with 30 days&apos; written notice</li>
            <li>Third-party platform costs (ad spend, API fees) are your responsibility</li>
            <li>Refunds handled on a case-by-case basis</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">8. Disclaimers and Limitation of Liability</h2>
          <p>THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
          <p>We do not guarantee specific business outcomes, ROI, conversion rates, or performance results. AI recommendations are suggestions, not guarantees. We are not liable for third-party platform outages, API changes, or policy updates.</p>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY SHALL NOT EXCEED FEES PAID IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. WE SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">9. Indemnification</h2>
          <p>You agree to indemnify Vaibrant from claims arising from your content (including AI-generated content you approved), your violation of third-party platform policies, these Terms, or applicable law.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">10. Suspension and Termination</h2>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>We may suspend for non-payment, policy violations, or security concerns</li>
            <li>We may terminate with 30 days&apos; notice, or immediately for material breach</li>
            <li>You may terminate at any time through your account settings or written notice</li>
            <li>Upon termination, data handled per our <Link href="/privacy" className="text-foreground underline underline-offset-4">Privacy Policy</Link></li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">11. Data Protection</h2>
          <p>Governed by our <Link href="/privacy" className="text-foreground underline underline-offset-4">Privacy Policy</Link>. For business customers whose data we process, the <Link href="/dpa" className="text-foreground underline underline-offset-4">Data Processing Agreement</Link> also applies.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">12. Governing Law</h2>
          <p>These Terms are governed by applicable law without regard to conflict of law principles. Disputes shall be resolved through good-faith negotiation first, followed by binding arbitration if necessary.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">13. Changes</h2>
          <p>We may modify these Terms with 30 days&apos; notice. Continued use after changes take effect constitutes acceptance.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight text-foreground">14. Contact</h2>
          <div className="bg-surface border border-border/50 rounded-xl p-5">
            <p className="text-white/80">Questions: <strong>info@vaibrant.co</strong></p>
            <p className="text-white/80 mt-1">Vaibrant Agency &middot; vaibrant.agency</p>
          </div>
        </section>
      </div>
    </article>
  );
}
